default: &default
  adapter: postgresql
  encoding: unicode
  host:postgresql
  username: postgres
  password: Hos$7500
  pool: 5

development:
  <<: *default
  database: suncalc_development

test:
  <<: *default
  database: suncalc_test

production:
  <<: *default
  database: coursera_postgresql
