default: &default
  adapter: postgresql
  encoding: unicode
  host: dpg-cqmm6btds78s73918e2g-a
  username: coursera_postgresql_user
  password: eUnn7zpPs2em4bTaj1NAAT7QM9oXDBIX
  pool: 5

development:
  <<: *default
  database: suncalc_development

test:
  <<: *default
  database: suncalc_test

production:
  <<: *default
  database: coursera_postgresql
