default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

production:
  <<: *default
  host: tamaak-acdamy2
  database: coursera_postgresql
  username: coursera_postgresql_user
  password: eUnn7zpPs2em4bTaj1NAAT7QM9oXDBIX
  
